version: "3.9"

services:
  frontend:
    build: .
    volumes:
      - .:/app:cached
    ports:
      - "5173:5173"
      - "24678:24678"
    tty: true
    command: sh -c "npm install && npm run dev"
networks:
  coffee_kaiwai_network:
    external: true
